### ISSUE TITLE
Need a way to cancel the storage reservation

### ISSUE THREAD

**Issue by renqiz** [drvcoin/drive#38]
Especially when failing to create drive, there is no record on the client side for the successfully reserved space on some host. This is going to cause the space to be "lost". The client should always record what have been reserved and use that for next retry (either automatically or manually) and for cancellation.

**Comment by shobs55** [comment]
#40 Commit 28adc5a4bbb8881b2c395d12aade2aa4ec834f95
-  drive saves the config file for partial failed reservations
-  drive saves the config file in tmp location if not run as sudo
-  drive accepts config file path with argument -f 
-  Delete volume of drive will unreserve whatever space was reserved on host and republish new space to kad
